---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-ap6-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-backstage/my-quarkus-ap6-gitops.git